import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/Header/Navbar';
import HeroSection from '../components/HeroSection';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="absolute top-0 left-0 w-screen h-screen bg-primary overflow-hidden">
        <NavBar />
        <HeroSection />
      </main>
    </>
  );
};

export default Home;
